### ISSUE TITLE
Question: How do I?

### ISSUE THREAD

**Issue by janemiceli** [rabbitmq/rabbitmq-perf-html#2]
I really like the chart on send-msg-rate and recv-msg-rate with latency, how do I remote one or the other (send/receive) from the graph and change the scale to understand the data better?

**Comment by michaelklishin** [comment]
@videlalvaro is this possible? Can we at least recommend some docs to the JS libraries used?

**Comment by videlalvaro** [comment]
The library uses http://www.flotcharts.org/

To have this feature we would have to modify the current `perf.js` lib to be able to obtain the list of fields from the HTML

**Comment by michaelklishin** [comment]
@videlalvaro thanks. If you feel you'd have some bandwidth for this after `3.5.0`, please file an issue with more specific requirements. I'm going to close this question.
